export const suppressionJustificationPattern =
  " -- ds-exception: [A-Z]+-[0-9]+ | .+";

export const designSystemPolicy = {
  legacyMode: "strict",
  approvedComponents: new Set([
    "Layout",
    "Section",
    "ScanCard",
    "StatusBadge",
    "Divider",
    "PageHeader",
    "EmptyStateCard",
    "SkeletonList",
  ]),
  approvedRawElements: new Set([
    "html",
    "head",
    "meta",
    "title",
    "script",
    "style",
    "body",
    "nav",
    "strong",
    "a",
    "div",
    "h1",
    "h2",
    "h3",
    "p",
    "form",
    "label",
    "input",
    "button",
    "ul",
    "li",
    "span",
    "section",
    "header",
    "article",
    "hr",
    "details",
    "summary",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    "pre",
  ]),
  forbiddenRawElements: new Set(["marquee", "blink", "center", "font"]),
  approvedClassPatterns: [
    /^(sm:|md:|lg:)?(hover:|first:|last:)?(bg|border|text|divide)-(background|card|error|foreground|muted|primary|success|warning)(\/(5|10|25|30|90))?$/,
    /^(sm:|md:|lg:)?(hover:)?(rounded|rounded-(md|lg|full))$/,
    /^(sm:|md:|lg:)?(hover:)?(block|flex|grid|hidden|inline-flex)$/,
    /^(sm:|md:|lg:)?(items|justify)-(start|center|between)$/,
    /^(sm:|md:|lg:)?(flex-col|flex-row)$/,
    /^(sm:|md:|lg:)?(gap|space-y|p|px|py|pt|pb|pl|pr|mt|mb|ml|mx|w|max-w)-([0-9]+|0\.5|1\.5|4xl|48|full)$/,
    /^(sm:|md:|lg:)?grid-cols-([0-9]+)$/,
    /^(sm:|md:|lg:)?(font-(sans|mono|medium|semibold)|capitalize|truncate)$/,
    /^(sm:|md:|lg:)?(text-(xs|sm|lg|xl|left|right)|underline|break-words)$/,
    /^(sm:|md:|lg:)?(overflow-x-auto|cursor-pointer|shrink-0|transition-colors|list-disc)$/,
  ],
  approvedClassTokens: new Set([
    "bg-background",
    "bg-card",
    "bg-error/10",
    "bg-error/5",
    "bg-muted",
    "bg-primary",
    "bg-primary/10",
    "bg-success/10",
    "bg-warning/10",
    "block",
    "border",
    "border-0",
    "border-b",
    "border-border",
    "border-error/25",
    "border-error/30",
    "border-muted",
    "border-primary/30",
    "border-success/25",
    "border-t",
    "border-warning/25",
    "border-warning/30",
    "break-words",
    "capitalize",
    "cursor-pointer",
    "divide-muted",
    "divide-y",
    "first:pt-0",
    "flex",
    "flex-col",
    "font-medium",
    "font-mono",
    "font-sans",
    "font-semibold",
    "gap-2",
    "gap-3",
    "gap-4",
    "grid",
    "grid-cols-2",
    "hover:bg-muted",
    "hover:bg-primary/90",
    "inline-flex",
    "items-center",
    "items-start",
    "justify-between",
    "last:pb-0",
    "lg:grid-cols-3",
    "list-disc",
    "max-w-4xl",
    "mb-3",
    "mb-6",
    "ml-2",
    "mt-2",
    "mt-3",
    "mx-auto",
    "overflow-x-auto",
    "p-3",
    "p-4",
    "p-8",
    "pb-2",
    "pb-3",
    "pl-6",
    "pr-4",
    "pt-1",
    "px-2",
    "px-3",
    "px-4",
    "py-0.5",
    "py-1",
    "py-1.5",
    "py-2",
    "py-3",
    "rounded",
    "rounded-full",
    "rounded-lg",
    "rounded-md",
    "shrink-0",
    "sm:flex-row",
    "sm:grid-cols-2",
    "sm:items-start",
    "sm:justify-between",
    "sm:text-right",
    "space-y-1",
    "space-y-2",
    "space-y-3",
    "space-y-4",
    "space-y-6",
    "text-error",
    "text-error-foreground",
    "text-foreground",
    "text-left",
    "text-lg",
    "text-muted-foreground",
    "text-primary",
    "text-primary-foreground",
    "text-sm",
    "text-success",
    "text-warning",
    "text-xl",
    "text-xs",
    "transition-colors",
    "truncate",
    "underline",
    "w-48",
    "w-full",
  ]),
  forbiddenClassPatterns: [
    /^(bg|text|border)-[a-z]+-[0-9]{2,3}$/,
    /^!/, 
  ],
  approvedStyleProps: [],
  forbiddenProps: new Set(["style", "dangerouslySetInnerHTML"]),
  suppressionRules: {
    allowedDirective: "eslint-disable-next-line",
    allowedRulePrefix: "custom/ds-",
    requireTicket: true,
    justificationPattern: /--\s*ds-exception:\s*[A-Z]+-[0-9]+\s*\|\s*.+$/,
    disallowedDirectives: [
      "eslint-disable",
      "eslint-disable-line",
      "eslint-enable",
      "@ts-ignore",
    ],
  },
  dynamicClassAllowlist: {
    byFile: {
      "src/views/components/Divider.tsx": ["classes"],
      "src/views/components/ScanCard.tsx": ["classes"],
      "src/views/components/Section.tsx": ["classes"],
      "src/views/components/StatusBadge.tsx": ["classes"],
    },
    allowedExpressionKinds: ["Literal", "TemplateLiteral", "ConditionalExpression"],
  },
};
