export const suppressionJustificationPattern = ' -- ds-exception: [A-Z]+-[0-9]+ | .+';

export const designSystemPolicy = {
	legacyMode: 'strict',
	approvedComponents: new Set([
		'Layout',
		'Section',
		'ScanCard',
		'StatusBadge',
		'Divider',
		'PageHeader',
		'EmptyStateCard',
		'SkeletonList',
		'Icon',
	]),
	approvedRawElements: new Set([
		'html',
		'head',
		'meta',
		'title',
		'link',
		'script',
		'style',
		'body',
		'nav',
		'footer',
		'strong',
		'a',
		'div',
		'h1',
		'h2',
		'h3',
		'p',
		'form',
		'label',
		'input',
		'button',
		'ul',
		'li',
		'span',
		'section',
		'header',
		'article',
		'hr',
		'details',
		'summary',
		'table',
		'thead',
		'tbody',
		'tr',
		'th',
		'td',
		'pre',
		'time',
		'svg',
		'path',
		'circle',
		'line',
		'polyline',
		'g',
	]),
	forbiddenRawElements: new Set(['marquee', 'blink', 'center', 'font']),
	approvedClassPatterns: [
		/^(sm:|md:|lg:)?(hover:|first:|last:)?(bg|border|text|divide)-(background|card|error|foreground|muted|primary|success|warning)(\/(5|10|25|30|90))?$/,
		/^(sm:|md:|lg:)?(hover:)?(rounded|rounded-(md|lg|xl|full))$/,
		/^(sm:|md:|lg:)?(hover:)?(block|flex|grid|hidden|inline-flex|sticky)$/,
		/^(sm:|md:|lg:)?(items|justify)-(start|center|between)$/,
		/^(sm:|md:|lg:)?(flex-col|flex-row)$/,
		/^(sm:|md:|lg:)?(gap|space-y|p|px|py|pt|pb|pl|pr|mt|mb|ml|mx|w|max-w|h|min-h)-([0-9]+|0\.5|1\.5|4xl|5xl|6xl|48|full|auto|screen)$/,
		/^(sm:|md:|lg:)?grid-cols-([0-9]+)$/,
		/^(sm:|md:|lg:)?(font-(sans|mono|medium|semibold)|capitalize|truncate)$/,
		/^(sm:|md:|lg:)?(text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|left|right|center)|underline|break-words)$/,
		/^(sm:|md:|lg:)?(overflow-x-auto|cursor-pointer|shrink-0|transition-colors|list-disc|top-0|z-\d+)$/,
	],
	approvedClassTokens: new Set([
		'bg-background',
		'bg-card',
		'bg-error/10',
		'bg-error/5',
		'bg-foreground',
		'bg-muted',
		'bg-primary',
		'bg-primary/10',
		'bg-success/10',
		'bg-warning/10',
		'block',
		'border',
		'border-0',
		'border-b',
		'border-border',
		'border-error/25',
		'border-error/30',
		'border-muted',
		'border-primary/30',
		'border-success/25',
		'border-t',
		'border-warning/25',
		'border-warning/30',
		'break-words',
		'capitalize',
		'cursor-pointer',
		'divide-muted',
		'divide-y',
		'first:pt-0',
		'flex',
		'flex-col',
		'font-medium',
		'font-mono',
		'font-sans',
		'font-semibold',
		'gap-2',
		'gap-3',
		'gap-4',
		'gap-6',
		'gap-8',
		'gap-10',
		'grid',
		'grid-cols-1',
		'grid-cols-2',
		'grid-cols-3',
		'h-4',
		'h-5',
		'h-6',
		'hover:bg-muted',
		'hover:bg-primary/90',
		'inline-flex',
		'items-center',
		'items-start',
		'justify-between',
		'last:pb-0',
		'lg:grid-cols-3',
		'list-disc',
		'max-w-4xl',
		'max-w-6xl',
		'md:grid-cols-3',
		'mb-3',
		'mb-6',
		'min-h-screen',
		'ml-2',
		'mt-2',
		'mt-3',
		'mx-auto',
		'overflow-x-auto',
		'p-3',
		'p-4',
		'p-6',
		'p-8',
		'pb-2',
		'pb-3',
		'pl-6',
		'pr-4',
		'pt-1',
		'pt-20',
		'pt-32',
		'px-2',
		'px-3',
		'px-4',
		'py-0.5',
		'py-1',
		'py-1.5',
		'py-2',
		'py-3',
		'py-6',
		'py-10',
		'py-20',
		'rounded',
		'rounded-full',
		'rounded-lg',
		'rounded-md',
		'rounded-xl',
		'shrink-0',
		'sm:flex-col',
		'sm:flex-row',
		'sm:grid-cols-2',
		'sm:items-start',
		'sm:justify-between',
		'sm:px-6',
		'sm:text-right',
		'space-y-1',
		'space-y-2',
		'space-y-3',
		'space-y-4',
		'space-y-6',
		'sticky',
		'text-background',
		'text-error',
		'text-error-foreground',
		'text-foreground',
		'text-left',
		'text-lg',
		'text-muted-foreground',
		'text-primary',
		'text-primary-foreground',
		'text-sm',
		'text-success',
		'text-warning',
		'text-xl',
		'text-xs',
		'text-base',
		'text-2xl',
		'text-3xl',
		'text-4xl',
		'text-5xl',
		'text-center',
		'top-0',
		'transition-colors',
		'truncate',
		'underline',
		'w-48',
		'w-full',
		'w-5',
		'w-6',
		'z-50',
	]),
	forbiddenClassPatterns: [/^(bg|text|border)-[a-z]+-[0-9]{2,3}$/, /^!/],
	approvedStyleProps: [],
	forbiddenProps: new Set(['style', 'dangerouslySetInnerHTML']),
	suppressionRules: {
		allowedDirective: 'eslint-disable-next-line',
		allowedRulePrefix: 'custom/ds-',
		requireTicket: true,
		justificationPattern: /--\s*ds-exception:\s*[A-Z]+-[0-9]+\s*\|\s*.+$/,
		disallowedDirectives: ['eslint-disable', 'eslint-disable-line', 'eslint-enable', '@ts-ignore'],
	},
	dynamicClassAllowlist: {
		byFile: {
			'src/views/components/Divider.tsx': ['classes'],
			'src/views/components/ScanCard.tsx': ['classes'],
			'src/views/components/Section.tsx': ['classes'],
			'src/views/components/StatusBadge.tsx': ['classes'],
			'src/views/components/icons.tsx': ['classString'],
		},
		allowedExpressionKinds: ['Literal', 'TemplateLiteral', 'ConditionalExpression'],
	},
};
